/**
 * Central mock data for UI development.
 * Used when NEXT_PUBLIC_USE_MOCK=true in .env.local
 */

export const MOCK_USER = {
  id: "mock-user-001",
  name: "Demo User",
  email: "demo@marktech.ai",
};

export const MOCK_SESSION = {
  user: MOCK_USER,
  session: { id: "mock-session-001", userId: MOCK_USER.id, expiresAt: "2099-01-01" },
};

export const MOCK_BRAND = {
  id: "mock-brand-001",
  name: "TechNova",
  adminEmail: "admin@technova.ai",
  website: "https://technova.ai",
  phone: "+1234567890",
  phoneCountryCode: "+1",
  industry: "SaaS Technology",
  companyInfo: "TechNova builds AI-powered productivity tools for modern teams.",
  toneOfVoice: "Professional yet approachable",
  guidelines: "Use clean, minimal design. Avoid clutter.",
  onboardingCompleted: true,
  createdAt: "2026-01-01T00:00:00Z",
  updatedAt: "2026-01-01T00:00:00Z",
};

export const MOCK_BRAND_KIT = {
  id: "mock-kit-001",
  brandId: MOCK_BRAND.id,
  primaryColor: "#2563EB",
  secondaryColor: "#1E40AF",
  accentColor: "#F59E0B",
  fonts: [{ name: "Inter", weight: 400 }, { name: "Space Grotesk", weight: 700 }],
  toneOfVoice: "Professional yet approachable",
  guidelines: "Use clean, minimal design.",
  logos: ["https://picsum.photos/seed/logo/200/200"],
  backgrounds: ["https://picsum.photos/seed/bg1/1200/800"],
  graphics: [],
  actors: [],
  brandBrief: { strategy: "Empower teams with AI", themes: ["productivity", "AI"], hooks: ["Work smarter"] },
  do: ["Use brand colors", "Keep it minimal"],
  dont: ["Use clutter", "Use off-brand fonts"],
};

export const MOCK_AUDIENCES = [
  {
    id: "mock-audience-001",
    brandId: MOCK_BRAND.id,
    name: "Tech-Savvy Millennials",
    demographics: { ageRange: "25-35", gender: ["all"], location: ["US", "UK", "India"] },
    interests: ["technology", "AI", "productivity", "startups"],
    personas: [],
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "mock-audience-002",
    brandId: MOCK_BRAND.id,
    name: "Enterprise Decision Makers",
    demographics: { ageRange: "35-50", gender: ["all"], location: ["US", "Europe"] },
    interests: ["enterprise software", "ROI", "digital transformation"],
    personas: [],
    createdAt: "2026-01-02T00:00:00Z",
  },
];

export const MOCK_CAMPAIGNS = [
  {
    id: "mock-campaign-001",
    brandId: MOCK_BRAND.id,
    audienceId: MOCK_AUDIENCES[0].id,
    name: "Chinese New Year 2026",
    category: "Brand Awareness",
    channels: ["Instagram", "Facebook"],
    aspectRatio: "9:16",
    objective: "AWARENESS",
    budget: 5000,
    currency: "USD",
    timezone: "UTC",
    startDate: "2026-01-28T00:00:00Z",
    endDate: "2026-02-15T00:00:00Z",
    promptType: "GUIDED",
    status: "ACTIVE",
    tags: ["CNY", "festive"],
    keyMessages: ["Celebrate the Year of the Snake", "Unity and Prosperity"],
    campaignBreif: {
      strategy: "A vibrant Chinese New Year campaign targeting tech-savvy millennials. The campaign celebrates cultural heritage through modern digital storytelling, combining traditional motifs with contemporary design aesthetics. Focus on themes of unity, prosperity, and new beginnings.",
      themes: ["celebration", "tradition", "prosperity", "unity"],
      hooks: ["Ring in the Year of the Snake", "Where tradition meets tomorrow", "Prosperity starts here"]
    },
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "mock-campaign-002",
    brandId: MOCK_BRAND.id,
    audienceId: MOCK_AUDIENCES[1].id,
    name: "Summer Product Launch",
    category: "Lead Generation",
    channels: ["LinkedIn", "Twitter"],
    aspectRatio: "16:9",
    objective: "CONVERSIONS",
    budget: 10000,
    currency: "USD",
    timezone: "America/New_York",
    startDate: "2026-06-01T00:00:00Z",
    endDate: "2026-08-31T00:00:00Z",
    promptType: "ADVANCED",
    status: "DRAFT",
    tags: ["launch", "summer"],
    keyMessages: ["Introducing TechNova 3.0"],
    campaignBreif: null,
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
];

export const MOCK_CREATIVES = [
  {
    id: "mock-creative-001",
    campaignId: MOCK_CAMPAIGNS[0].id,
    type: "IMAGE",
    status: "GENERATED",
    url: "https://picsum.photos/seed/creative1/800/1000",
    guidedBackgroundUrl: "https://picsum.photos/seed/creative1/800/1000",
    guidedLogoUrl: "https://picsum.photos/seed/logo/200/200",
    promptType: "GUIDED",
    adCopy: "Wishing you joy, luck, and prosperity this Lunar New Year.",
    headlines: ["Happy Chinese New Year 2026"],
    callToAction: "Shop Now",
    creativeBrief: "Background: Cherry blossom forest scene with red and pink tones in a natural setting.\n\nActors: Chinese pair in festive attire, conveying celebration and happiness.\n\nGraphics: 2D style new year lanterns featuring lanterns and hangings.\n\nText: Headline \"Chinese New Year\" with tagline \"A celebration of traditions, unity, and prosperity\" in Mayfest font.",
    createdAt: new Date(Date.now() - 60000).toISOString(),
    updatedAt: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: "mock-creative-002",
    campaignId: MOCK_CAMPAIGNS[0].id,
    type: "IMAGE",
    status: "GENERATED",
    url: "https://picsum.photos/seed/creative2/800/1000",
    promptType: "GUIDED",
    adCopy: "A celebration of traditions, unity, and prosperity.",
    headlines: ["Chinese New Year"],
    callToAction: "Learn More",
    creativeBrief: "Background: Cherry blossom forest scene with red and pink tones.\n\nActors: Chinese pair in festive attire.\n\nGraphics: 2D lanterns and decorative elements.\n\nText: Headline \"Chinese New Year\" in Mayfest font.",
    createdAt: new Date(Date.now() - 50000).toISOString(),
    updatedAt: new Date(Date.now() - 50000).toISOString(),
  },
  {
    id: "mock-creative-003",
    campaignId: MOCK_CAMPAIGNS[0].id,
    type: "IMAGE",
    status: "GENERATED",
    url: "https://picsum.photos/seed/creative3/800/1000",
    promptType: "GUIDED",
    adCopy: "Ring in the Year of the Snake with style.",
    headlines: ["Year of the Snake"],
    callToAction: "Explore",
    creativeBrief: null,
    createdAt: new Date(Date.now() - 40000).toISOString(),
    updatedAt: new Date(Date.now() - 40000).toISOString(),
  },
  {
    id: "mock-creative-004",
    campaignId: MOCK_CAMPAIGNS[0].id,
    type: "IMAGE",
    status: "GENERATED",
    url: "https://picsum.photos/seed/creative4/800/1000",
    promptType: "GUIDED",
    adCopy: "Bring your brand to life this festive season.",
    headlines: ["Festive Season"],
    callToAction: "Get Started",
    creativeBrief: null,
    createdAt: new Date(Date.now() - 30000).toISOString(),
    updatedAt: new Date(Date.now() - 30000).toISOString(),
  },
  {
    id: "mock-creative-006",
    campaignId: MOCK_CAMPAIGNS[0].id,
    type: "BLOG",
    status: "GENERATED",
    url: null,
    promptType: "GUIDED",
    adCopy: null,
    headlines: [],
    callToAction: null,
    creativeBrief: null,
    blogData: {
      title: "5 Ways TechNova Is Redefining Productivity for the Year of the Snake",
      content_markdown: `# 5 Ways TechNova Is Redefining Productivity for the Year of the Snake\n\nAs we welcome the Year of the Snake — a symbol of wisdom, transformation, and renewal — there's no better time to reflect on how AI-powered tools are reshaping the way modern teams work.\n\n## 1. Smarter Workflows, Less Friction\n\nTechNova's AI engine learns your team's patterns and surfaces the right information at the right time. No more hunting through threads or missed context.\n\n## 2. Real-Time Collaboration Across Time Zones\n\nWith async-first design and intelligent summaries, TechNova keeps distributed teams aligned — whether you're in Singapore, London, or New York.\n\n## 3. Festive Season, Focused Execution\n\nThe Chinese New Year period is traditionally a time of reflection and new beginnings. TechNova helps teams close out Q1 goals with clarity and momentum.\n\n## 4. AI That Understands Your Brand\n\nFrom tone-of-voice consistency to on-brand content generation, TechNova's brand intelligence layer ensures every output feels authentically yours.\n\n## 5. Prosperity Through Productivity\n\nThe Year of the Snake is about strategic thinking and long-term vision. TechNova gives your team the tools to work smarter — not just harder.\n\n---\n\n*Ready to transform how your team works? [Get started with TechNova today](#).*`,
      summary: "Discover how TechNova's AI-powered platform is helping modern teams embrace the spirit of the Year of the Snake — with smarter workflows, real-time collaboration, and brand-consistent content generation.",
      tags: ["productivity", "AI", "Chinese New Year", "TechNova", "collaboration"],
      notes: "Tone: Professional yet approachable. Optimized for LinkedIn and company blog.",
    },
    createdAt: new Date(Date.now() - 10000).toISOString(),
    updatedAt: new Date(Date.now() - 10000).toISOString(),
  },
  {
    id: "mock-creative-005",
    campaignId: MOCK_CAMPAIGNS[0].id,
    type: "VIDEO",
    status: "GENERATED",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    promptType: "GUIDED",
    adCopy: "A festive video for Chinese New Year.",
    headlines: ["Happy New Year"],
    callToAction: "Watch Now",
    creativeBrief: "Visuals: Chinese pair in a cherry blossom forest with natural daylight lighting.\n\nMotion: Dolly zoom camera movement with cut transitions. Slow push in on the couple with quick cuts between festive scenes.\n\nFormat: 9:16 aspect ratio, 8 seconds duration.\n\nAudio: Energetic mood. Traditional Chinese music with modern beats.",
    createdAt: new Date(Date.now() - 20000).toISOString(),
    updatedAt: new Date(Date.now() - 20000).toISOString(),
  },
];

export const USE_MOCK = process.env.NEXT_PUBLIC_USE_MOCK === "true" || process.env.USE_MOCK === "true";
